#! /usr/bin/env python
# -*- coding: iso-8859-1 -*-

# ---------------------------------------------------------------------------
#
# $Id: constants.py,v 2.10 2005/05/12 22:05:17 kdm Exp $
#
# ---------------------------------------------------------------------------
#
# Diese Datei enthaelt alle Konstanten, die im Projekt benutzt werden. Von
# der Erweiterung des Dictionaries MESSAGE_TEXT wird dringend abgeraten. Bei
# Updates kann es ansonsten zu Konflikten kommen, wenn durch Aenderungen der
# Release das dict erweitert wurde.
#
# ---------------------------------------------------------------------------

# Nachrichtentexte
MESSAGE_TEXT = {}
MESSAGE_TEXT[1]   = "Fehlerhafte Startzeile."
MESSAGE_TEXT[2]   = "Fehlerhafte Endzeile."
MESSAGE_TEXT[3]   = "Befehl vor Zugbeginn: %s"
MESSAGE_TEXT[4]   = "Befehl nach Zugende: %s"
MESSAGE_TEXT[5]   = "Unbekannter Befehl: %s"
MESSAGE_TEXT[6]   = "Einheit %d nicht gefunden."
MESSAGE_TEXT[7]   = "Befehl %s: Falscher Parametertyp"
MESSAGE_TEXT[8]   = "Befehl %s: Falsche Parameteranzahl"
MESSAGE_TEXT[9]   = "Befehl %s ohne %s"
MESSAGE_TEXT[10]  = "Befehl %s konnte keiner Einheit zugeordnet werden."
MESSAGE_TEXT[11]  = "Falscher Parametertyp, %s erwartet."
MESSAGE_TEXT[12]  = "Unbekanntes Bauwerk %s."
MESSAGE_TEXT[13]  = "Objektid %d nicht in Region vorhanden."
MESSAGE_TEXT[14]  = "Einheit %d konnte keiner Region zugeordnet werden."
MESSAGE_TEXT[15]  = "Unbekannter Gegenstand %s."
MESSAGE_TEXT[16]  = "Unbekanntes Talent %s."
MESSAGE_TEXT[17]  = "Unbekannte Einheit %d"
MESSAGE_TEXT[18]  = "Falsche Parteinummer"
MESSAGE_TEXT[19]  = "Mehrere lange Befehle"
MESSAGE_TEXT[20]  = "Gebaeude befindet sich schon im Bau."
MESSAGE_TEXT[21]  = "Gebaeude ist nicht ausbaubar."
MESSAGE_TEXT[22]  = "Einheit ist nicht Besitzer des Objekts."
MESSAGE_TEXT[23]  = "Einheit ist nicht eingeschifft."
MESSAGE_TEXT[24]  = "Gebaeude befindet sich nicht im Bau."
MESSAGE_TEXT[25]  = "Einheit hat nicht die Voraussetzungen, um das Gebaeude zu bauen."
MESSAGE_TEXT[26]  = "Einheit hat nicht genuegend Baumaterial."
MESSAGE_TEXT[27]  = "Gebaeude existiert schon in der Region."
MESSAGE_TEXT[28]  = "Unbekannter Ansiedlungstyp in (%d,%d,%s)"
MESSAGE_TEXT[29]  = "Unbekanntes Terrain in (%d,%d,%s)"
MESSAGE_TEXT[30]  = "Einheit wird aufgeloest."
MESSAGE_TEXT[31]  = "Langer Befehl ist unbekannt."
MESSAGE_TEXT[32]  = "Kampfzauber ist unbekannt."
MESSAGE_TEXT[33]  = "Einheit hat nicht gezaubert."
MESSAGE_TEXT[34]  = "Die Partei hat noch %d freie Politikpunkte."
MESSAGE_TEXT[35]  = "Die Partei verwendet zu viele Politikpunkte."
MESSAGE_TEXT[36]  = "Die Partei kann noch zusaetzliche Magier ruesten."
MESSAGE_TEXT[37]  = "Einheit hat zu wenig Silber, um sich ernaehren zu koennen."
MESSAGE_TEXT[38]  = "Unbekannte Befehlssyntax."
MESSAGE_TEXT[39]  = "Unbekanntes Objekt (Id: %d)"
MESSAGE_TEXT[40]  = "Gebaeude %s existiert schon."
MESSAGE_TEXT[41]  = "Produkt fuer Produktionsgebaeude nicht in Region vorhanden."
MESSAGE_TEXT[42]  = "Es ist nicht genuegend Silber im Reichsschatz."
MESSAGE_TEXT[43]  = "Zu befoerdernde Einheit befindet sich nicht im Gebaeude."
MESSAGE_TEXT[44]  = "Belagernde Einheit besitzt keine Belagerungsgeraete."
MESSAGE_TEXT[45]  = "Belagernde Einheit besitzt nicht genuegend Belagerungsgeraete."
MESSAGE_TEXT[46]  = "Region gehoert nicht zum eigenen Reich."
MESSAGE_TEXT[47]  = "Keine Ansiedlung in der Region."
MESSAGE_TEXT[48]  = "Region wurde bereits besiedelt."
MESSAGE_TEXT[49]  = "Nur Einheiten der eigenen Stammrasse koennen besiedeln."
MESSAGE_TEXT[50]  = "Region wird bereits durch eine andere Partei besiedelt."
MESSAGE_TEXT[51]  = "Region wird bereits durch eine andere eigene Einheit besiedelt."
MESSAGE_TEXT[52]  = "Getarnte Einheiten koennen nicht besiedeln."
MESSAGE_TEXT[53]  = "Einheit hat nicht genuegend Personen zum Besiedeln."
MESSAGE_TEXT[54]  = "Unbewaffnete Einheit kann nicht bewachen."
MESSAGE_TEXT[55]  = "Einheit besitzt den Gegenstand %s nicht."
MESSAGE_TEXT[56]  = "Einheit besitzt den Gegenstand %s nicht in ausreicheder Menge."
MESSAGE_TEXT[57]  = "Unbewaffnete Einheit kann keine Steuern treiben."
MESSAGE_TEXT[58]  = "Einheit hat keine Schiffe zum Flotten bilden."
MESSAGE_TEXT[59]  = "Unbewaffnete Einheit kann nicht erobern."
MESSAGE_TEXT[60]  = "Einheit hat nicht genuegend Bewaffnete zum Erobern."
MESSAGE_TEXT[61]  = "Region gehoert schon zum eigenen Reichsgebiet."
MESSAGE_TEXT[62]  = "Region ist schon neutrales Gebiet."
MESSAGE_TEXT[63]  = "Region wird schon durch eine andere eigene Einheit erobert."
MESSAGE_TEXT[64]  = "Region wurde bereits gefoerdert."
MESSAGE_TEXT[65]  = "Ansiedlung wurde bereits gefoerdert."
MESSAGE_TEXT[66]  = "Nicht genuegend Geld zum Foerdern in der Region."
MESSAGE_TEXT[67]  = "Einheit kann nicht ubergeben werden, falsche Rasse."
MESSAGE_TEXT[68]  = "Einheit darf nicht mehrere Schiffstypen besitzen."
MESSAGE_TEXT[69]  = "Rassen duerfen innerhalb einer Einheit nicht gemischt werden."
MESSAGE_TEXT[70]  = "Es wurde bereits eine Glaubenstendenz gewaehlt."
MESSAGE_TEXT[71]  = "Es wurde bereits eine Hauptgottheit gewaehlt."
MESSAGE_TEXT[72]  = "Einheit ist kein Magier."
MESSAGE_TEXT[73]  = "Produkt %s kann in dieser Region nicht gekauft werden."
MESSAGE_TEXT[74]  = "Produkt %s kann nicht mehr gekauft werden, die Kapazitaet in der Region ist erschoepft."
MESSAGE_TEXT[75]  = "Produkt %s kann nicht mehr in ausreichender Menge gekauft werden"
MESSAGE_TEXT[76]  = "Es ist nicht genuegend Silber zum Kauf des Produkts vorhanden."
MESSAGE_TEXT[77]  = "Nur Anfuehrer koennen andere Einheiten lehren."
MESSAGE_TEXT[78]  = "Einheit kann keine weiteren Schueler lehren (%d/%d)."
MESSAGE_TEXT[79]  = "Einheit kann das Talent %s nicht lehren."
MESSAGE_TEXT[80]  = "Einheit kann das Talent %s nicht erlernen."
MESSAGE_TEXT[81]  = "Einheit ist bereits Meister des Faches %s."
MESSAGE_TEXT[82]  = "Das Talent %s kann nicht erlernt werden."
MESSAGE_TEXT[83]  = "Einheit kann nicht so viele Schurkenbefehle ausfuehren."
MESSAGE_TEXT[84]  = "Region wurde gepluendert, kein Treiben mehr moeglich."
MESSAGE_TEXT[85]  = "Diesem Gott opfert schon die Einheit %d."
MESSAGE_TEXT[86]  = "Einheit beherrscht das benoetigte Talent nicht."
MESSAGE_TEXT[87]  = "Unbewaffnete Einheit kann nicht pluendern."
MESSAGE_TEXT[88]  = "Einheit hat ein oder mehrere Verbauchsgueter zum Produzieren nicht."
MESSAGE_TEXT[89]  = "Produkt %s kann in der Region nicht produziert werden."
MESSAGE_TEXT[90]  = "Einheit muss zum hindurch-Reisen ein Objekt betreten."
MESSAGE_TEXT[91]  = "Einheit kann sich nicht bewegen."
MESSAGE_TEXT[92]  = "Einheit kann sich nicht schwimmend bewegen."
MESSAGE_TEXT[93]  = "Einheit ist ueberladen."
MESSAGE_TEXT[94]  = "Einheit hat nicht genuegend Bewegungspunkte."
MESSAGE_TEXT[95]  = "Einheit kann nicht auf Land schwimmen."
MESSAGE_TEXT[96]  = "Flotte kann kein Gebaeude betreten."
MESSAGE_TEXT[97]  = "Der Einheit %d kann das Talent %s nicht weiter beigebracht werden."
MESSAGE_TEXT[98]  = "Einheit befindet sich nicht auf einer Flotte."
MESSAGE_TEXT[99]  = "Einheit ist der Kapitaen der Flotte und muss mit Reise die Richtung angeben."
MESSAGE_TEXT[100] = "Einheit beherrscht das angegebene Talent %s nicht."
MESSAGE_TEXT[101] = "Gegenstand %s ist keine waehlbare Stammrasse."
MESSAGE_TEXT[102] = "Es wurde bereits eine Stammrasse gewaehlt."
MESSAGE_TEXT[103] = "Produkt %s kann in dieser Region nicht verkauft werden."
MESSAGE_TEXT[104] = "Produkt %s kann nicht mehr verkauft werden, die Kapazitaet in der Region ist erschoepft."
MESSAGE_TEXT[105] = "Einheit kann den Gegenstand %s nicht verwerten."
MESSAGE_TEXT[106] = "Einheit hat nicht das notwenige Talent zum Zerstoeren."
MESSAGE_TEXT[107] = "Einheit hat nicht genug Talentlevel, um das Gebaeude zu zerstoeren."
MESSAGE_TEXT[108] = "Es sind nicht mehr genuegend Arbeitsplaetze frei."
MESSAGE_TEXT[109] = "Es sind keine Arbeitsplaetze mehr frei."
MESSAGE_TEXT[110] = "Eine unbewaffnete Einheit kaempft."
MESSAGE_TEXT[111] = "Region hat ihre maximale Groesse erreicht."
MESSAGE_TEXT[112] = "Talente werden durch Einheit %d eventuell verwaessert."
MESSAGE_TEXT[113] = "Talent %s ist kein bekannter Kampfzauber."
MESSAGE_TEXT[114] = "Schueler %d hat keinen Lerne-Befehl."
MESSAGE_TEXT[115] = "Die Politikpunkte werden mehrfach neu gesetzt."
MESSAGE_TEXT[116] = "Einheit kann nicht mehr genuegend Silber erpluendern."
MESSAGE_TEXT[117] = "Einheit kann in dieser Region kein Silber mehr erpluendern."
MESSAGE_TEXT[118] = "Einheit bewegt sich durch ein Objekt hindurch. Keine Prognose der Zielregion moeglich."
MESSAGE_TEXT[119] = "Einheit durchquert eine unbekannte Region."
MESSAGE_TEXT[120] = "Einheit kann nicht mehr genuegend Steuern eintreiben."
MESSAGE_TEXT[121] = "Einheit kann in dieser Region kein Silber mehr eintreiben."
MESSAGE_TEXT[122] = "Einheit kann nicht mehr genuegend Silber durch Unterhaltung einnehmen."
MESSAGE_TEXT[123] = "Einheit kann in dieser Region kein Silber mehr durch Unterhaltung einnehmen."
MESSAGE_TEXT[124] = "Talent %s ist kein bekannter Zauber."
MESSAGE_TEXT[125] = "Nur Einheiten von freundlichen oder alliierten Parteien koennen das Gebaeude uebergeben werden."
MESSAGE_TEXT[126] = "Partei ist nicht Besitzer des Gebaeudes, betreten koennte fehl schlagen."
MESSAGE_TEXT[127] = "Einheit wird geopfert."
MESSAGE_TEXT[128] = "Region wird schon durch anderes Reich bewacht."
MESSAGE_TEXT[129] = "Vermeide-Flag wurde geloescht."
MESSAGE_TEXT[130] = "Tarnung der Einheit wird aufgehoben"
MESSAGE_TEXT[131] = "Einheit konnte den Gegenstand %s nicht in ihren Besitz bringen."
MESSAGE_TEXT[132] = "Einheit konnte nicht die angegebene Menge des Gegenstandes %s sammeln."
MESSAGE_TEXT[133] = "Der Befehl %s ist nur ein Alias, bitte %s benutzen."
MESSAGE_TEXT[134] = "Bewache-Flag wurde geloescht."
MESSAGE_TEXT[135] = "Darauf achten, dass die vertretende Partei die Auswertung erhaelt (Befehl Adresse)"
MESSAGE_TEXT[136] = "Einheit rueckt vor."
MESSAGE_TEXT[137] = "Einheit befindet sich nicht in einem Objekt."
MESSAGE_TEXT[138] = "Region wird bereits von einer anderen Partei erobert."
MESSAGE_TEXT[139] = "Region besitzt kein bekanntes Terrain."
MESSAGE_TEXT[140] = "Ansiedlung besitzt keinen bekannten Typ."
MESSAGE_TEXT[141] = "Einheit kann das Produkt %s nicht in ausreichender Menge abbauen (%d statt %d)."
MESSAGE_TEXT[142] = "Einheit kann das Produkt %s nicht mehr abbauen."
MESSAGE_TEXT[143] = "Fuer den Gegenstand %s sind keine Bewegungspunkte bekannt (Fehlender Conf-Eintrag)."
MESSAGE_TEXT[144] = "Fuer den Gegenstand %s ist keine Tragkraft bekannt (Fehlender Conf-Eintrag)."
MESSAGE_TEXT[145] = "Fuer den Gegenstand %s ist kein Gewicht bekannt (Fehlender Conf-Eintrag)."
MESSAGE_TEXT[146] = "Objekt fuer Kommando %s konnte nicht erzeugt werden."
MESSAGE_TEXT[147] = "Einheit hat nicht genuegend Geld zum Lernen."
MESSAGE_TEXT[148] = "Bauwerk %s ist nicht errichtbar."
MESSAGE_TEXT[149] = "Einheit befindet sich nicht in einem Gebaeude."
MESSAGE_TEXT[150] = "Einheit nimmt %d Silber durch %s ein."
MESSAGE_TEXT[151] = "Einheit produziert %d %s."
MESSAGE_TEXT[152] = "Flotte %d konnte nicht gefunden werden."
MESSAGE_TEXT[153] = "Unbekannter Kampfzauber %s."
MESSAGE_TEXT[154] = "Kapitaen verlaesst nicht leere Flotte."
MESSAGE_TEXT[155] = "Einheit wurde automatisch ausgeschifft, da die Flotte aufgeloest wurde."
MESSAGE_TEXT[156] = "Flotte kann nicht durch irgendwas hindurch reisen."
MESSAGE_TEXT[157] = "Die Partei verwendet im Bereich %s mehr PP als gesetzt."
MESSAGE_TEXT[158] = "Talente wurden durch den Zukauf von Personen verwaessert."
MESSAGE_TEXT[159] = "Bestehende Flotten koennen nicht erneut einschiffen."
MESSAGE_TEXT[160] = "Nicht genuegend Geld zum Kauf der angegebenen Menge %s vorhanden."


#allgemeine Fehlertexte
ERR_MISSING_AW_GROUP = "Erste CR-Gruppe muss 'Auswertung' heissen"


#Diplomatische Positionen
DIPLOMACY_ALLIED     = "Alliiert"
DIPLOMACY_FRIENDLY   = "Freundlich"
DIPLOMACY_NEUTRAL    = "Neutral"
DIPLOMACY_UNFRIENDLY = "Unfreundlich"
DIPLOMACY_HOSTILE    = "Feindlich"


# Welten
WORLD_RORQUAL = "Rorqual"
WORLD_ABYSS   = "Abyss"
WORLD_HOVECAN = "Hovecan"
WORLD_ELYSIUM = "Elysium"


# Talent-Typen
TYPE_T_MAGIC       = "Magie"
TYPE_T_SPELL       = "Zauber"
TYPE_T_COMBATSPELL = "Kampfzauber"


# Objekt-Typen
TYPE_O_PROTECTION = "Wachgebaeude"
TYPE_O_CITY       = "Stadtgebaeude"
TYPE_O_PRODUCTION = "Produktion"
TYPE_O_RAMPART    = "Wall"


# Produkt-Typen
TYPE_P_TRADE      = "type_trade"
TYPE_P_HUMANOID   = "type_humanoid"
TYPE_P_MONSTER    = "type_monster"
TYPE_P_MAGIC      = "type_magic"
TYPE_P_WEAPON     = "type_weapon"
TYPE_P_RACEWEAPON = "type_raceweapon"
TYPE_P_ARMOUR     = "type_armour"
TYPE_P_MOUNT      = "type_mount"
TYPE_P_SHIELD     = "type_shield"
TYPE_P_SHIP       = "type_ship"
TYPE_P_FOOD       = "type_food"


# Stadt-Typen
TYPE_HS_ABANDONED_VILLAGE = "Verlassene Ortschaft"
TYPE_HS_SETTLEMENT        = "Siedlung"
TYPE_HS_SMALL_VILLAGE     = "Kleines Dorf"
TYPE_HS_VILLAGE           = "Dorf"
TYPE_HS_SMALL_TOWN        = "Kleinstadt"
TYPE_HS_CITY              = "Stadt"
TYPE_HS_LARGE_CITY        = "Grosse Stadt"
TYPE_HS_METROPOLIS        = "Metropole"


# Terrain-Typen
TYPE_TER_PLAIN             = "Ebene"
TYPE_TER_HIGHLANDS         = "Hochland"
TYPE_TER_CAVERN            = "Kaverne"
TYPE_TER_OCEAN             = "Ozean"
TYPE_TER_DESERT            = "Wueste"
TYPE_TER_MOUNTAINS         = "Bergland"
TYPE_TER_JUNGLE            = "Dschungel"
TYPE_TER_SWAMP             = "Sumpf"
TYPE_TER_TUNDRA            = "Tundra"
TYPE_TER_TUNNEL            = "Tunnel"
TYPE_TER_SUBMONTANE_FOREST = "Unterirdischer Wald"
TYPE_TER_FOREST            = "Wald"
TYPE_TER_ABYSS             = "Abyss"


# Bewegungsarten
MOVE_SWIMMING = "schwimmend"
MOVE_WALKING  = "gehend"
MOVE_RIDING   = "reitend"
MOVE_FLYING   = "fliegend"


# Flags
FLAG_BACKWARD      =  0  # Hinten
FLAG_AVOID         =  1  # Vermeide
FLAG_HOLD_POSITION =  2  # Halte
FLAG_REVEAL_UNIT   =  3  # Offenbare Einheit
FLAG_REVEAL_PARTY  =  4  # Offenbare Partei
FLAG_MASKED        =  5  # Getarnt
FLAG_SINGLE        =  6  # Einzeln
FLAG_GUARD         =  7  # Bewache
FLAG_TAXING        =  8  # Dauersteuer, Treibe
FLAG_SUPPLY        =  9  # Versorge
FLAG_CONSUME_PARTY = 10  # Verbrauche Partei
FLAG_CONSUME_UNIT  = 11  # Verbrauche Einheit
FLAG_SACRIFICED    = 12  # wird Geopfert
FLAG_TRANSFERED    = 13  # wird Uebergeben
FLAG_BESIEGE       = 14  # belagere
FLAG_PLUNDER       = 15  # pluendere
FLAG_KEEP_ALL      = 16  # behaelt Alles
FLAG_CONJURE       = 17  # hat Gezaubert
FLAG_TEACH         = 18  # lehrt
FLAG_REVEAL        = 19  # Offenbare


#Richtungen
DIR_NORTH     = "n"
DIR_NORTHEAST = "no"
DIR_NORTHWEST = "nw"
DIR_SOUTH     = "s"
DIR_SOUTHEAST = "so"
DIR_SOUTHWEST = "sw"


# Gegenstaende
ID_P_ANFU = "ANFU"
ID_P_SILB = "SILB"
ID_P_BG   = "BG"
ID_P_STEI = "STEI"


# Talente
ID_T_SEGE = "SEGE"
ID_T_UNTE = "UNTE"
ID_T_BAUM = "BAUM"


# Gebauede
NAME_B_ZITA = "Zitadelle"
NAME_B_GARN = "Garnison"


# sonstiges
DIV_MASTER  = "Meister"
DIV_WEATHER = "naechsten Monat wird Lejla uns wieder gutes Wetter bescheren"
DIV_WALL    = "Wall in Bau"


# CR-Idents
IDENT_REPORT             = "Auswertung"
IDENT_DIPLOMACY          = "Diplomatische Position"
IDENT_MOVE               = "Spielzug"
IDENT_MONTH              = "Monat"
IDENT_YEAR               = "Jahr"
IDENT_PARTYNAME          = "Parteiname"
IDENT_OPTED_RACE         = "Stammrasse"
IDENT_TREASURY           = "Reichsschatz"
IDENT_POPULATION         = "Personen gesamt"
IDENT_RELIGION           = "Glaubenstendenz"
IDENT_GOD                = "Hauptgottheit"
IDENT_ETS                = "ETS"
IDENT_VERSION            = "Version"
IDENT_EMAIL              = "E-Mail"
IDENT_GAME_START         = "Spieleinstieg"
IDENT_PARTYNUMBER        = "Parteinummer"
IDENT_WAR_PP             = "Kriegspunkte"
IDENT_TRADE_PP           = "Handelspunkte"
IDENT_MAGIC_PP           = "Magiepunkte"
IDENT_CONTACT            = "Kontakt"
IDENT_QUANTITY_LEADERS   = "Anfuehrer gesamt"
IDENT_QUANTITY_REGULARS  = "Regulaere gesamt"
IDENT_OWN_UNITS          = "Eigene Einheiten"
IDENT_FRAGMENTATION      = "Zersplitterungsfaktor"
IDENT_ARMED              = "Bewaffnete"
IDENT_PROPORTION_LEADERS = "Anteil Anfuehrer"
IDENT_RANKING            = "Rang"
IDENT_INCOME_ENTIRE      = "Einkommen gesamt"
IDENT_PP_ENTIRE          = "PP gesamt"
IDENT_WAR_PP_USED        = "Kriegspunkte verbraucht"
IDENT_TRADE_PP_USED      = "Handelspunkte verbraucht"
IDENT_MAGIC_PP_USED      = "Magiepunkte verbraucht"
IDENT_WAR_PP_MAX         = "Kriegspunkte max."
IDENT_TRADE_PP_MAX       = "Handelspunkte max."
IDENT_MAGIC_PP_MAX       = "Magiepunkte max."
IDENT_WAR_MAX            = "Krieg max."
IDENT_MAGICIANS_MAX      = "Magier max."
IDENT_TRADE_MAX          = "Handel max."
IDENT_GAME               = "Game"

IDENT_MSG_BATTLES            = "Kaempfe"
IDENT_MSG_DISPATCH           = "Botschaften"
IDENT_MSG_CONTACTS           = "Kontakte"
IDENT_MSG_ERRORS             = "Fehler"
IDENT_MSG_EVENTS             = "Ereignisse"
IDENT_MSG_TALENTS            = "Talentberichte"
IDENT_MSG_TRANSFERS          = "Uebergaben"
IDENT_MSG_PRODUCTION         = "Produziertes"
IDENT_MSG_TRADE              = "An- und Verkaeufe"
IDENT_MSG_INCOME             = "Einkommen"
IDENT_MSG_FOREIGN_ACTIVITIES = "Fremdaktivitaeten"
IDENT_MSG_MAGIC              = "Magisches"

IDENT_DIPLOMACY_STANDARD    = "Standard"

IDENT_REGION                = "Region"
IDENT_REGION_PRODUCTS       = "Produkte"
IDENT_REGION_PURCHASE       = "Ankauf"
IDENT_REGION_SALE           = "Verkauf"
IDENT_REGION_WAYS           = "Wege"
IDENT_REGION_OWN            = "Eigenes"
IDENT_REGION_HINTERLAND     = "Umland"
IDENT_REGION_X              = "x"
IDENT_REGION_Y              = "y"
IDENT_REGION_WORLD          = "Ort"
IDENT_REGION_TERRAIN        = "Terrain"
IDENT_REGION_TERRITORY      = "Reichsgebiet"
IDENT_REGION_SHORT_REPORT   = "Kurzbericht"
IDENT_REGION_WAGES          = "Loehne"
IDENT_REGION_MAX_WORK       = "Max.Arbeit"
IDENT_REGION_TAXES          = "Steuersilber"
IDENT_REGION_ENTERTAINMENT  = "Unterhaltung"
IDENT_REGION_RACE           = "Rasse"
IDENT_REGION_PEASANTS       = "Bauern"
IDENT_REGION_MINDER         = "Bewacher"
IDENT_REGION_POPULATION     = "Regionsbauern"
IDENT_REGION_MAX_POPULATION = "Einwohnermax"
IDENT_REGION_PROVINCE       = "Provinz"
IDENT_REGION_WEATHER        = "Wetter"
IDENT_REGION_JOBS           = "Max.Arbeiter"
IDENT_REGION_NAME           = "Name"
IDENT_REGION_WALL           = "Wall"
IDENT_REGION_DIMGATE        = "Dimensionstor"
IDENT_REGION_BUILD_COST     = "Ansiedlungsbau"

IDENT_HOMESTEAD            = "Ansiedlung"
IDENT_HOMESTEAD_NAME       = "Name"
IDENT_HOMESTEAD_TYPE       = "Typ"
IDENT_HOMESTEAD_POPULATION = "Stadtbauern"

IDENT_PRODUCT          = "Produkt"
IDENT_PRODUCT_KEY      = "Abk"
IDENT_PRODUCT_SINGULAR = "Singular"
IDENT_PRODUCT_COST     = "Preis"
IDENT_PRODUCT_AMOUNT1  = "Menge"
IDENT_PRODUCT_AMOUNT2  = "Anzahl"
IDENT_PRODUCT_NAME1    = "Ware"
IDENT_PRODUCT_NAME2    = "Gegenstand"
IDENT_PRODUCT_WEIGHT   = "Gewicht"

IDENT_OBJECT             = "Objekt"
IDENT_OBJECT_KEY         = "Id"
IDENT_OBJECT_SINGULAR    = "Typ"
IDENT_OBJECT_HINTERLAND  = "Umland"
IDENT_OBJECT_UNKNOWN     = "Unbekannt"
IDENT_OBJECT_SIZE        = "aktuell"
IDENT_OBJECT_NAME        = "Name"
IDENT_OBJECT_DESCRIPTION = "Beschreibung"
IDENT_OBJECT_RUNES       = "Runen"
IDENT_OBJECT_UNTREADABLE = "Unbetretbar"

IDENT_UNIT               = "Einheit"
IDENT_UNIT_KEY           = "Id"
IDENT_UNIT_NAME          = "Name"
IDENT_UNIT_PARTY         = "Reich"
IDENT_UNIT_INVENTORY     = "Inhalt"
IDENT_UNIT_TALENT        = "Talent"
IDENT_UNIT_LEARNABLE     = "Erlernbar"
IDENT_UNIT_CAN_LEARN     = "Kann lernen"
IDENT_UNIT_COMBAT_SPELL  = "Kampfzauber"
IDENT_UNIT_REVEAL_PARTY  = "Offenbart Partei"
IDENT_UNIT_REVEAL_UNIT   = "Offenbart Einheit"
IDENT_UNIT_MASKED        = "Getarnt"
IDENT_UNIT_HOLD_POSITION = "Haelt Stellung"
IDENT_UNIT_BACKWARD      = "Hinten"
IDENT_UNIT_AVOID         = "Vermeide"
IDENT_UNIT_SINGLE        = "Einzeln"
IDENT_UNIT_GUARD         = "Bewacht"
IDENT_UNIT_TAXING        = "Dauersteuer"
IDENT_UNIT_SUPPLY        = "Versorgt"
IDENT_UNIT_CONSUME_PARTY = "Parteinahrung verbrauchen"
IDENT_UNIT_CONSUME_UNIT  = "Einheitsnahrung verbrauchen"
IDENT_UNIT_SETTLING      = "Besiedlung"
IDENT_UNIT_EMBARKED      = "Eingeschifft"
IDENT_UNIT_CONQUERING    = "Eroberung"
IDENT_UNIT_DESCRIPTION   = "Beschreibung"
IDENT_UNIT_CAP_WALK      = "Bel.Gehend"
IDENT_UNIT_CAP_MAX_WALK  = "Bel.GehendMax"
IDENT_UNIT_CAP_RIDE      = "Bel.Reitend"
IDENT_UNIT_CAP_MAX_RIDE  = "Bel.ReitendMax"
IDENT_UNIT_CAP_SWIM      = "Bel.Schwimmend"
IDENT_UNIT_CAP_MAX_SWIM  = "Bel.SchwimmendMax"
IDENT_UNIT_CAP_FLY       = "Bel.Fliegend"
IDENT_UNIT_CAP_MAX_FLY   = "Bel.FliegendMax"
IDENT_UNIT_EXPARTYNUMBER = "ExReich"
IDENT_UNIT_EXPARTYNAME   = "ExReichsname"
IDENT_UNIT_MASKERADE     = "Tarnung"
IDENT_UNIT_STATUS1       = "Status1"
IDENT_UNIT_STATUS2       = "Status2"
IDENT_UNIT_STATUS3       = "Status3"
IDENT_UNIT_STATUS4       = "Status4"

IDENT_TALENT       = "Talent"
IDENT_TALENT_KEY   = "Abk"
IDENT_TALENT_LEVEL = "Stufe"
IDENT_TALENT_XP    = "Xp"
IDENT_TALENT_TITEL = "Titel"
IDENT_TALENT_NAME  = "Name"

IDENT_LANE_DIRECTION = "Nach"
IDENT_LANE_X              = "x"
IDENT_LANE_Y              = "y"
IDENT_LANE_WORLD          = "Ort"
IDENT_LANE_TERRAIN        = "Terrain"
IDENT_LANE_NAME           = "Name"
IDENT_LANE_PROVINCE       = "Provinz"
IDENT_LANE_HOMESTEAD      = "Ansiedlung"
IDENT_LANE_HOMESTEAD_TYPE = "Ansiedlungstyp"
IDENT_LANE_WALL           = "Wall"
IDENT_LANE_FLAG_BAN       = "Banngebiet"

IDENT_WALL_DIRECTION = "Nach"
IDENT_WALL_TYPE      = "Typ"

IDENT_OWN_SUM_LEADER           = "Summe Anfuehrer"
IDENT_OWN_SUM_REGULARS         = "Summe Regulaere"
IDENT_OWN_LIVELIHOOD           = "Unterhalt"
IDENT_OWN_LAST_TAXES           = "Vormonat Steuer"
IDENT_OWN_LAST_ENTERTAINMENT   = "Vormonat Unterhaltung"
IDENT_OWN_LAST_WORK            = "Vormonat Arbeit"

KB_BOOL_OR                      = "Or"
KB_BOOL_AND                     = "And"
KB_BOOL_NOT                     = "Not"
KB_BOOL_PRODUCT                 = "Produkt"
KB_BOOL_PRODUCTTYPE             = "Produkttyp"
KB_BOOL_TALENT                  = "Talent"
KB_BOOL_TALENTTYPE              = "Talenttyp"
KB_BOOL_TALENTLEVEL             = "TalentLevel"
KB_BOOL_BUILDING                = "Objekt"
KB_PRODUCT_AMOUNT               = "Menge"
KB_PRODUCT_COUNT                = "Anzahl"
KB_PRODUCT_ID                   = "Abk"
KB_PRODUCT_WEIGHT               = "Gewicht"
KB_PRODUCT_SINGULAR             = "Singular"
KB_PRODUCT_PLURAL               = "Plural"
KB_PRODUCTTYPE_TYPE             = "Typ"
KB_PRODUCTTYPE_AMOUNT           = "Menge"
KB_PRODUCT_CONSUMPTION          = "Verbrauch"
KB_PRODUCT_CAPACITY             = "Tragkraft"
KB_PRODUCT_BP                   = "BP"
KB_PRODUCT_TYPE                 = "Typ"
KB_PRODUCT_NEEDS_FOR_USE        = "Benoetigt zum Gebrauch"
KB_PRODUCT_NEEDS_FOR_RECYCLING  = "Benoetigt zum Verwerten"
KB_PRODUCT_NEEDS_FOR_PRODUCTION = "Benoetigt zur Produktion"
KB_TALENT_ID                    = "Abk"
KB_TALENT_LEVEL                 = "Stufe"
KB_TALENTTYPE_TYPE              = "Typ"
KB_TALENTTYPE_LEVEL             = "Stufe"
KB_TALENTLEVEL_ID               = "Abk"
KB_TALENTLEVEL_LEVEL            = "Level"
KB_TALENT_TYPE                  = "Typ"
KB_TALENT_LEARNCOST             = "Lernkosten"
KB_TALENT_SINGULAR              = "Singular"
KB_TALENT_NEEDS_FOR_LEARNING    = "Benoetigt zum Erlernen"
KB_BUILDING_ID                  = "Abk"
KB_BUILDING_SINGULAR            = "Singular"
KB_BUILDING_TYPE                = "Typ"
KB_BUILDING_MAX_SIZE            = "max. Groesse"
KB_BUILDING_MIN_SIZE            = "min. Groesse"
KB_BUILDING_ENTERABLE           = "betretbar"
KB_BUILDING_AIDS                = "beguenstigt"
KB_BUILDING_NEEDS_FOR_PRODUCION = "Benoetigt zur Produktion"
KB_BUILDING_PLURAL              = "Plural"
KB_BUILDING_ALIAS               = "Alias"
KB_BUILDING_EXPANDABLE          = "Ausbaubar"
KB_IDENT_PRODUCTSPEC            = "Produktspec"
KB_IDENT_BUILDINGSPEC           = "Objektspec"
KB_IDENT_TALENTSPEC             = "Talentspec"
KB_IDENT_VERSION                = "Version"
KB_IDENT_PRODUCT_OPTABLE_RACE   = "Stammrasse"
KB_IDENT_PRODUCT_LIVELIHOOD     = "Lebensunterhalt"